name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: list files
      run: ls -la
    - name: Check main.c
      run: cat MyProject/main.c || echo "main.c not found"
