name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile project
      run: gcc MyProject/main.c -o MyProject/main

    - name: Run project
      run: ./MyProject/main
